name: tests

on: [push]

jobs:
  build:
    name: Browser
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: urlhub_test
        ports:
          - 33306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    strategy:
      matrix:
        php-version: ['8.0']

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP ${{ matrix.php-version }}
        uses: shivammathur/setup-php@v2 #https://github.com/shivammathur/setup-php
        with:
          php-version: ${{ matrix.php-version }}

      # https://github.com/marketplace/actions/setup-php-action#cache-composer-dependencies
      - name: Get Composer Cache Directory
        id: composercache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Cache Dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composercache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install Dependencies
        run: |
          composer -V
          composer install --no-interaction --ignore-platform-reqs
      - name: Setup Laravel
        env:
          DB_PORT: ${{ job.services.mysql.ports[3306] }}
        run: |
          cp .env.testing .env
          php artisan config:clear
          php artisan migrate --seed
          php artisan dusk:chrome-driver `/opt/google/chrome/chrome --version | cut -d " " -f3 | cut -d "." -f1`
          ./vendor/laravel/dusk/bin/chromedriver-linux &
          php artisan serve &
      - name: Run Automated Browser Testing
        env:
          APP_URL: "http://127.0.0.1:8000"
          DB_PORT: ${{ job.services.mysql.ports[3306] }}
        run: php artisan dusk
